### ISSUE TITLE
Add author info to front matter in blog post archetype

### ISSUE THREAD

**Issue by shelbyspees** [adhdevops/adhdevops.club#4]
```yaml
author
  name: "Shelby Spees"
  url: "https://shelbyspees.com"
  pronouns: "she/her or they/them"
```
